### PR TITLE
Add dots to headers gpl3

### PR DESCRIPTION
**Pull request by garex**
Here we have: http://www.gnu.org/licenses/gpl.html

`0. Definitions.` in MD version — not `0. Definitions`

``` bash
sed -i 's/^\(###.*[^\.]\)$/\1./' gnu-gpl-v3.0.md
```

### CODE REVIEW

**Comment by IQAndreas** [comment]
Actually, both of those formatting decisions were made on purpose:

**Uppercase main header**

There are a few other licenses which also use uppercase letters, but were replaced with "title casing" when they were converted to Markdown. I believe that when the licenses were originally written, the use of uppercase was to show that the line was not a sentence, nor even a paragraph, but a title. If they had formatting to show that the line of text is a header (as we do in HTML and Markdown), I believe they would have used that, rather than use uppercase letters.

**Periods in headers**

I was taught that [periods in headers are gramatically incorrect](http://english.stackexchange.com/q/32884/5438). I'm not sure why they used periods in the headers. My best guess is perhaps were common at the time and have fallen into disuse.

**Comment by IQAndreas** [comment]
I'm going to close this issue as `wontfix`, but if you have any counter-arguments or good reasons to keep the periods, let me know. I can always re-open the issue with the click of a button.

Also, hats off for using `sed`. I respect people who use scripts to automate tasks like that, rather than going through line by line editing things manually. [_see_](https://plus.google.com/+BrunoOliveira/posts/MGxauXypb1Y?pid=5694023113460433314&oid=102451193315916178828)

**Comment by garex** [comment]
Counter-arg is simple — origin has it and legally dot is matter. Your project entitled as "A collection of open source licenses in Markdown format." So you are a **formatter** and not _restyler_.

Even comma matters:
- Execute him we should not, pardon him!
- Execute him, we should not pardon him!

So if Shakespeare has written something that is not in same style as another authors, publisher will not reformat it's style to be same.

**Comment by garex** [comment]
commandlinefu.com is our Bible ))

**Comment by IQAndreas** [comment]
> Counter-arg is simple — origin has it and legally dot is matter. _[...]_ You are a **formatter** and not _restyler_.

Good point.

But as a counter-counter-argument, **legally**, I would argue that [the placement of the periods in those specific titles](https://github.com/garex/markdown-licenses/commit/62621dd67a6b0d8ab66a29f5b41f8902614b8263) have no impact on the meaning of the text, and therefore make no legal difference:

```
0. Definitions.
0. Definitions

1. Source Code.
1. Source Code

4. Conveying Verbatim Copies.
4. Conveying Verbatim Copies
```

And **grammatically**, the lines in question are not complete sentences, and therefore, have no reason to contain periods.

**Comment by garex** [comment]
Are you a professional lawyer? Contact one regarding legal difference and the "origin" term.

**Comment by garex** [comment]
Now I see — this commit is all that evil 4f71fa64205b62fe70d3bdf44e0cb405bf06b4fc

**Pull request closed without merging**
